### PR TITLE
Proper fixes

### PR DESCRIPTION
**Pull request by ropery**
Should be good to go now.

### CODE REVIEW

**Comment by acabal** [comment]
None of these changes matches the page scans. _Tristram Shandy_ is a unique book where most regular conventions on dashes and italics are not followed. Are you using different page scans to compare against?

**Comment by ropery** [comment]
Firstly, the scan I'm checking against is [the selfsame](https://archive.org/details/in.ernet.dli.2015.285840) listed on the SE book page. The emendations [8b97f1e](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/8b97f1e70692620d5d053a4373968f4f8db7f9fe), [c6a1913](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/c6a1913426b26efce9381ff5fdae0674c522febb), [79e4618](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/79e4618d8cdc26d5f5b8cafc4c14eb6143810d52), [78f50c4](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/78f50c452e550b8cb9b205fcfb8b6f1fb8d078b0) are all done to match that.

Secondly, we're not adhering 100% to the scans, are we? I un-italicize "Slop" ([f1e44cd](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/f1e44cdd375082a1db36ef2e122577f588f30f7e)) because Sterne always italicizes names, and here it's a case of italicization upon italicization. [3fdfafb](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/3fdfafb0006b44f775653a29429d69a326bfb296) is a clear misprint, so I correct it. [65b783f](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/pull/8/commits/65b783fec2448317254377e6de4f0f4639d756a1) is a missing punctuation in the scanned page, but I explained my reasoning in the commit message.

**Comment by acabal** [comment]
OK. So we need to remove 8b97f1e and 79e4618. We want to keep the existing blockquote structure, and in the scans it's a comma which leads into the next chapter as a stylistic point, so we can keep it.

**Comment by ropery** [comment]
> OK. So we need to remove [8b97f1e](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/commit/8b97f1e70692620d5d053a4373968f4f8db7f9fe) and [79e4618](https://github.com/standardebooks/laurence-sterne_the-life-and-opinions-of-tristram-shandy-gentleman/commit/79e4618d8cdc26d5f5b8cafc4c14eb6143810d52).

> in the scans it's a comma which leads into the next chapter as a stylistic point, so we can keep it.

Which is what I do with 79e4618, replacing `.` with `,` according to the scans. Why *remove* 79e4618?

> We want to keep the existing blockquote structure

Perhaps I didn't explain myself clearly in the commit message in 8b97f1e. As [the online view](https://standardebooks.org/ebooks/laurence-sterne/the-life-and-opinions-of-tristram-shandy-gentleman/text/chapter-2-17) shows, the first `“Trust!⁠⸺⁠` line is, unlike in the scans, indented, in contradistinction to the second. Which prompted me to look into the HTML. Search `blockquote` in the HTML, and we see the second set of `<blockcquote>`s surround a whole block of text encompassing Trim's reading of the sermon (paragraphs starting with `“`) *and* the interruptions (paragraphs in square brackets). Therefore, in agreement to this, we move the first closing `</blockquote>` to after the square-bracketed interruption. For the same reason, the CSS is changed to apply the same style to both blockquotes.

Now whether this is the best structure/styling is up to debate, but this commit only aims to bring consistency between the two blocks.

**Pull request merged**
